services:
  backend:
    build:
      context: ./backend
    container_name: accessibility-sandbox-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=${PORT}
      - DB_PATH=${DB_PATH}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_data:/app/data

  frontend:
    build:
      context: ./frontend
    container_name: accessibility-sandbox-frontend
    ports:
      - "5173:5173"
    environment:
       - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  backend_data: